# Generated by Django 5.2.4 on 2025-07-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jobpost_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('job', 'freelancer')},
        ),
    ]
