# Generated by Django 5.2.4 on 2025-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_proposal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
